"""add pole position fields to race

Revision ID: 3a01bf7c4d68
Revises: 55079b849fc6
Create Date: 2026-06-18 11:19:30.123006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a01bf7c4d68'
down_revision = '55079b849fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pole_pilot_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pole_time', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key('fk_race_pole_pilot', 'pilot_profile', ['pole_pilot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.drop_constraint('fk_race_pole_pilot', type_='foreignkey')
        batch_op.drop_column('pole_time')
        batch_op.drop_column('pole_pilot_id')
    # ### end Alembic commands ###
