"""Add fcm_token to PilotProfile

Revision ID: 55079b849fc6
Revises: bca631398eca
Create Date: 2026-03-14 11:46:02.182380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55079b849fc6'
down_revision = 'bca631398eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pilot_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcm_token', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pilot_profile', schema=None) as batch_op:
        batch_op.drop_column('fcm_token')

    # ### end Alembic commands ###
