"""Adiciona telefone ao perfil

Revision ID: 86988882a5d6
Revises: 
Create Date: 2026-01-19 22:51:23.375292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86988882a5d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pilot_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pilot_profile', schema=None) as batch_op:
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
